'use strict';
// Research doctrines. Every entry is fully wired into the simulation (see the `effects` comments and the
// helpers below, which the other systems query). `ai` hints tell the nation AI how to change behaviour.

const RESEARCH = [
  // ---- economy / logistics ----
  { id: 'war_economy', name: 'War Economy', tags: ['econ', 'aggro'], ai: { aggression: 1.4 }, tier: 2,
    short: '{+30% gold|g} while you are attacking another nation',
    desc: 'While you are attacking another nation, your gold income is 30% higher.',
    words: ['econ_buff', 'aggressive'], answers: ['easy_prey', 'weak_army', 'rich', 'ally_target'] },
  { id: 'mass_production', name: 'Mass Production', tags: ['econ', 'build'], ai: { build: 1.3 }, tier: 2,
    short: 'Buildings and walls cost {15% less|g}',
    desc: 'Every building and wall you build costs 15% less gold.',
    words: ['econ_buff'], answers: ['rich', 'econ_buff', 'populated'] },
  { id: 'industrial_mobilization', name: 'Industrial Mobilization', tags: ['econ'], ai: { build: 1.2 }, tier: 2,
    short: '{+25% gold income|g}, but {10% fewer max troops|r}',
    desc: 'Your gold income is 25% higher, but your maximum troops are 10% lower.',
    words: ['econ_buff'], answers: ['rich', 'econ_buff'] },
  { id: 'military_rail', name: 'Military Rail', tags: ['econ', 'defense'], ai: { factories: 2 }, tier: 2,
    short: '{+20% troop growth|g} with 2+ rail-linked factories; trains carry {2x gold|g}',
    desc: 'While you own 2 or more factories linked by rail, your troops grow 20% faster. Your trains also deliver twice as much gold.',
    words: ['rail_power', 'econ_buff'], answers: ['strong_army', 'industrial', 'giant'] },
  { id: 'strategic_logistics', name: 'Strategic Logistics', tags: ['aggro'], ai: { aggression: 1.2 }, tier: 2,
    short: 'Your attacks advance {25% faster|g}; your boats sail {50% faster|g}',
    desc: 'Your land attacks advance 25% faster and your transport boats sail 50% faster.',
    words: ['fast_attacks', 'aggressive'], answers: ['easy_prey', 'weak_army', 'overseas'] },
  { id: 'military_industrial', name: 'Military Industrial Complex', tags: ['mech', 'econ'], ai: { factories: 2, mechs: 1 }, tier: 3,
    short: 'Factories send trains {2x as often|g}; Mechs cost {25% less|g}',
    desc: 'Your factories send out trains twice as often, and Mechs cost 25% less.',
    words: ['mech_economy', 'econ_buff'], answers: ['mech_army', 'industrial'] },
  // ---- defense ----
  { id: 'defensive_position', name: 'Defensive Position', tags: ['defense'], ai: { posts: 2 }, tier: 1,
    short: 'Your Defense Posts fire at attackers using {15% of your troops|g}; garrison them for more',
    desc: 'Your Defense Posts fire at attackers in range, using 15% of your troops as firepower. Right-click a post to garrison 10% of your troops in it for extra firepower.',
    words: ['fortified'], answers: ['aggressive', 'strong_army', 'attacking_me_now', 'danger', 'fast_attacks'] },
  { id: 'coastal_defense', name: 'Coastal Defense Network', tags: ['defense', 'navy'], ai: { posts: 1.5 }, tier: 2,
    short: 'Coastal posts shoot {every enemy ship|p} at {2x range|g}, {1.5% of its health|p} a shell; landings near them lose {30% troops|p}',
    desc: "Your Defense Posts near the coast fire at every enemy ship (not only warships), at double range and a faster rate, each shell taking 1.5% of the ship's health. Boats that land near one of your posts lose 30% of their troops.",
    words: ['coastal_fort'], answers: ['naval', 'navy_heavy', 'invader', 'amphibious', 'bombardment', 'sub_threat'] },
  { id: 'hardened_infra', name: 'Hardened Infrastructure', tags: ['defense'], ai: {}, tier: 2,
    short: 'Your buildings {survive nukes|g} outside the blast core; walls take {half damage|g}',
    desc: "Your buildings survive a nuke unless they are in the blast's core, and your walls take half damage from everything.",
    words: ['nuke_hardened'], answers: ['nuclear', 'nuke_armed', 'cheap_nukes', 'mirv', 'bombers', 'nuked_me'] },
  { id: 'military_district', name: 'Military Districts', tags: ['defense', 'aggro'], ai: { aggression: 1.15 }, tier: 1,
    short: 'Each City gives {+375K max troops|g} (was 250K), but {30% less gold|r}',
    desc: 'Each of your Cities adds 375K to your maximum troops instead of 250K, but your gold income is 30% lower.',
    words: ['troop_heavy'], answers: ['strong_army', 'danger', 'giant', 'attacking_me_now'] },
  { id: 'fighter_networks', name: 'Fighter Networks', tags: ['air', 'defense'], ai: {}, tier: 1,
    short: 'Enemy bombers over your land are {shot down ~60%|p} of the time; your SAMs reach {+30 tiles|g}',
    desc: 'Enemy bombers flying over your land are usually shot down (about 60% of the time), and your SAM Launchers reach 30 tiles further.',
    words: ['air_defense'], answers: ['bombers', 'bomber_threat', 'airship_threat'] },
  // ---- mech doctrines ----
  { id: 'heavy_mech', name: 'Heavy Mech Doctrine', tags: ['mech', 'defense'], ai: { mechs: 1 }, tier: 2,
    short: 'Your Mechs have {2.5x health|g}, but move {40% slower|r}',
    desc: 'Your Mechs have 2.5 times the health but move 40% slower.',
    words: ['heavy_mechs'], answers: ['artillery_line', 'anti_mech', 'mech_army', 'fortified'] },
  { id: 'assault_mech', name: 'Assault Mech Doctrine', tags: ['mech', 'aggro'], ai: { mechs: 1, aggression: 1.2 }, tier: 2,
    short: 'Mech stomps are {wider (+2)|g} and break walls and posts {3x faster|p}',
    desc: "Your Mechs' stomp clears a wider area (+2 radius) and breaks walls and Defense Posts 3 times faster.",
    words: ['mech_breakers', 'aggressive'], answers: ['walled', 'fortified', 'coastal_fort'] },
  { id: 'mech_production', name: 'Mech Production', tags: ['mech', 'econ'], ai: { mechs: 2 }, tier: 3,
    short: 'Mechs cost {40% less|g} and you can field {1 more|g}',
    desc: 'Mechs cost 40% less and you can field one more.',
    words: ['mech_economy'], answers: ['mech_army', 'weak_army', 'strong_army'] },
  { id: 'mech_weapons', name: 'Mech Weapons Systems', tags: ['mech', 'aggro'], ai: { mechs: 1 }, tier: 2,
    short: 'Mech shells deal {+60% damage|g} and {destroy a building in one hit|p}',
    desc: 'Your Mech shells deal 60% more damage and destroy a building in a single hit.',
    words: ['mech_firepower'], answers: ['fortified', 'populated', 'industry_clump', 'artillery_line'] },
  { id: 'longrange_mech', name: 'Long-Range Mech Systems', tags: ['mech'], ai: { mechs: 1 }, tier: 2,
    short: 'Your Mechs fire {10 tiles further|g}',
    desc: 'Your Mechs can fire 10 tiles further.',
    words: ['mech_range'], answers: ['artillery_line', 'fortified', 'sam_covered'] },
  { id: 'rapidfire_mech', name: 'Rapid-Fire Mech Systems', tags: ['mech', 'aggro'], ai: { mechs: 1 }, tier: 3,
    short: 'Your Mechs fire and stomp {40% more often|g}',
    desc: 'Your Mechs fire and stomp 40% more often.',
    words: ['mech_firepower'], answers: ['mech_army', 'weak_army', 'fortified'] },
  { id: 'amphibious_mech', name: 'Amphibious Mechs', tags: ['mech', 'navy'], ai: { mechs: 1 }, tier: 2,
    short: "Mechs {walk across water|g}, take {95% of a warship's health|p} a shell, reveal subs within {30 tiles|p}",
    desc: "Your Mechs can walk across water. Each of their shells takes 95% of a warship's health, they fire 50% further at sea, and they reveal enemy submarines within 30 tiles.",
    words: ['amphibious', 'anti_navy'], answers: ['overseas', 'naval', 'navy_heavy', 'sub_threat', 'bombardment'] },
  // ---- navy ----
  { id: 'coastal_bombardment', name: 'Coastal Bombardment', tags: ['navy', 'aggro'], ai: { warships: 2, aggression: 1.1 }, tier: 2,
    short: 'Your Warships {shell enemy coasts|p} within 40 tiles; every 10 cost {+300K more|r}',
    desc: 'Your Warships shell enemy coastal land within 40 tiles, killing troops and turning the land neutral. Every 10 Warships you own add 300K to the price of the next one.',
    words: ['bombardment', 'naval'], answers: ['coastal', 'port_heavy', 'coastal_fort'] },
  { id: 'submarine_warfare', name: 'Submarine Warfare', tags: ['navy'], ai: { subs: 1 }, tier: 3,
    short: "Unlocks {Submarines|g}: hidden, and every 90s they fire {3 missiles SAMs can't stop|p}",
    desc: 'Unlocks Submarines. They stay hidden unless an enemy warship or amphibious mech comes close, and every 90 seconds each one fires 3 missiles that destroy a building each and cannot be stopped by SAMs.',
    words: ['sub_threat', 'naval'], answers: ['sam_covered', 'port_heavy', 'overseas', 'coastal'] },
  { id: 'nuclear_subs', name: 'Nuclear Submarines', tags: ['navy', 'nuke'], ai: { subs: 1, nukes: 1 }, tier: 3,
    short: 'Your Submarines can {launch atom bombs|g} from anywhere at sea',
    desc: 'Your Submarines can launch atom bombs (at the normal price) from anywhere at sea.',
    words: ['sub_nukes', 'nuclear'], answers: ['sam_covered', 'overseas', 'city_clump'] },
  { id: 'amphibious_warfare', name: 'Amphibious Warfare', tags: ['navy', 'aggro'], ai: { boats: 2 }, tier: 2,
    short: 'Boats carry {+50% troops|g}, sail {50% faster|g}; {5 boats|g} at sea instead of 3',
    desc: 'Your transport boats carry 50% more troops and sail 50% faster, and you can have 5 at sea at once instead of 3.',
    words: ['invader'], answers: ['overseas', 'coastal'] },
  { id: 'naval_mines', name: 'Naval Mines', tags: ['navy', 'defense'], ai: { mines: 1 }, tier: 1,
    short: 'Unlocks hidden {Naval Mines|g} (100K) that {sink the first enemy ship|p} within 2 tiles',
    desc: "Unlocks Naval Mines (100K each), placed at sea within 60 tiles of your ports. A mine sinks the first enemy ship or boat that passes within 2 tiles, and enemies can't see them.",
    words: ['mined'], answers: ['invader', 'naval', 'amphibious', 'navy_heavy'] },
  { id: 'naval_base', name: 'Naval Bases', tags: ['navy', 'econ'], ai: { warships: 1 }, tier: 2,
    short: '{+25% trade gold|g}, Warships repair {5x faster|g} at your ports, {+2 Warships|g}',
    desc: 'Your trade ships earn 25% more gold, your Warships repair 5 times faster near your ports, and you can have 2 more Warships.',
    words: ['naval', 'econ_buff'], answers: ['navy_heavy', 'naval', 'port_heavy'] },
  { id: 'dday', name: 'D-Day', tags: ['navy', 'aggro'], ai: { boats: 1.5 }, tier: 1,
    short: 'Boat landings arrive with {+15% troops|g} and take the beach {without losses|g}',
    desc: 'Your boat landings arrive with 15% more troops and take the landing tile without losses.',
    words: ['invader', 'aggressive'], answers: ['overseas', 'coastal_fort'] },
  // ---- air ----
  { id: 'strategic_bombers', name: 'Strategic Bombers', tags: ['air', 'aggro'], ai: { bombers: 1 }, tier: 2,
    short: "Unlocks {Bomber Strikes|g} (300K): {destroy one enemy building|p}, SAMs can't stop them",
    desc: "Unlocks Bomber Strikes (300K) from a Missile Silo: a bomber flies up to 250 tiles and destroys one enemy building. SAMs can't stop bombers - only the Fighter Networks doctrine can.",
    words: ['bombers'], answers: ['sam_covered', 'nuclear', 'research_hub', 'industrial', 'econ_buff'] },
  { id: 'close_air_support', name: 'Close Air Support', tags: ['air', 'aggro'], ai: { aggression: 1.25 }, tier: 2,
    short: 'Your attacks on other nations lose {25% fewer troops|g}',
    desc: 'Your attacks on other nations lose 25% fewer troops.',
    words: ['aggressive'], answers: ['strong_army', 'fortified', 'weak_army'] },
  // ---- strategic weapons ----
  { id: 'tactical_nukes', name: 'Tactical Nuclear Weapons', tags: ['nuke', 'aggro'], ai: { nukes: 2 }, tier: 2,
    short: 'Atom bombs cost {half as much|g} and silos reload {2x faster|g}, but blasts are {smaller|r}',
    desc: 'Your atom bombs cost half as much and your silos reload twice as fast, but the blast is smaller (an 8-tile core and 16-tile edge instead of 12 and 30).',
    words: ['nuclear', 'cheap_nukes'], answers: ['city_clump', 'clump_uncovered', 'populated', 'econ_buff'] },
  { id: 'mirv', name: 'MIRV Engineering', tags: ['nuke'], ai: { nukes: 1 }, tier: 3,
    short: 'Hydrogen bombs split into {5 warheads|p} spread over 45 tiles',
    desc: 'Your Hydrogen bombs split into 5 atom-sized warheads that land spread over 45 tiles around the target - much harder for SAMs to stop.',
    words: ['nuclear', 'mirv', 'sam_breaker'], answers: ['city_clump', 'sam_covered', 'populated', 'giant'] },
  { id: 'field_engineering', name: 'Field Engineering', tags: ['defense', 'mech'], ai: { defensive: 1, mechs: 1 }, tier: 2,
    short: 'Unlocks the {Repair Yard|g}; Artillery reaches {+15 tiles|g}, reloads {30% faster|g}, hits {+50%|g}',
    desc: 'Unlocks the Repair Yard, which heals your Mechs and rebuilds damaged walls nearby. Your Artillery Batteries also reach 15 tiles further, reload 30% faster and hit 50% harder.',
    words: ['anti_mech'], answers: ['mech_army', 'mech_force', 'heavy_mechs', 'mech_breakers', 'mech_firepower', 'navy_heavy'] },
  { id: 'megacity', name: 'Megacity Planning', tags: ['econ'], ai: { build: 1.1 }, tier: 3,
    short: 'Cities can reach {level 4|g}, which earns far more gold than level 3',
    desc: 'Your Cities can be upgraded to level 4, which earns far more gold than level 3.',
    words: ['econ_buff', 'populated'], answers: ['rich', 'econ_buff'] },
  { id: 'heavy_industry', name: 'Heavy Industry', tags: ['econ'], ai: { factories: 3 }, tier: 3,
    short: 'Factories can reach {level 4|g}; trains pay {+35% per level|g} above 2',
    desc: "Your Factories can be upgraded to level 4, and every factory level above 2 makes that factory's trains pay 35% more.",
    words: ['econ_buff', 'industrial'], answers: ['econ_buff', 'rail_network'] },
  { id: 'strategic_airlift', name: 'Strategic Airlift', tags: ['air'], ai: { airships: 2 }, tier: 3,
    short: 'Airships carry {10% of your troops|g} (was 5%), fly {50% faster|g} and {120 tiles further|g}',
    desc: 'Your Airships carry 10% of your troops instead of 5%, fly 50% faster and reach 120 tiles further.',
    words: ['airship_threat'], answers: ['sam_covered', 'walled', 'overseas', 'fortified'] },
  { id: 'airbase_network', name: 'Airbase Network', tags: ['air'], ai: { airships: 1 }, tier: 2,
    short: '{+1 Airship|g}, Airships {cost 30% less|g}, and SAMs {can sit next to your Airport|g}',
    desc: 'You can have one more Airship in the air, Airships cost 30% less, and you may build SAM Launchers right next to your Airport.',
    words: ['airship_threat'], answers: ['sam_covered', 'overseas'] },
  { id: 'airborne_doctrine', name: 'Airborne Doctrine', tags: ['air', 'aggro'], ai: { airships: 1, aggression: 1.1 }, tier: 2,
    short: 'Troops dropped by Airship land {35% stronger|g}',
    desc: 'Troops dropped by your Airships land 35% stronger.',
    words: ['airship_threat', 'aggressive'], answers: ['sam_covered', 'fortified', 'walled'] },
  { id: 'interceptor_screen', name: 'Interceptor Screen', tags: ['defense', 'air'], ai: { defensive: 1 }, tier: 2,
    short: 'Enemy Airships in range of your {SAMs or Airport|g} have a {45% chance to be shot down|p}',
    desc: 'Enemy Airships that fly within range of your SAM Launchers or your Airport have a 45% chance to be shot down (one roll per pass). Build SAMs where you expect airdrops.',
    words: ['anti_air', 'air_defense'], answers: ['airship_threat', 'airport'] },
  // ---- answers to SAM umbrellas ----
  { id: 'cluster_munitions', name: 'Cluster Munitions', tags: ['nuke', 'aggro'], ai: { nukes: 1, antiSam: 3 }, tier: 2,
    short: 'Unlocks the {Cluster Strike|g}: {8 small missiles|p} at once, and each SAM stops only one',
    desc: 'Unlocks the Cluster Strike (1.5M) from a Missile Silo: 8 small missiles fired at once that scatter over the target. Each SAM can only stop one missile per reload, so most of the volley gets through.',
    words: ['sam_breaker', 'nuclear'], answers: ['sam_clump', 'sam_covered', 'shot_my_missiles', 'city_clump'] },
  { id: 'decoy_warheads', name: 'Decoy Warheads', tags: ['nuke'], ai: { nukes: 1, antiSam: 2 }, tier: 2,
    short: 'When a SAM fires at your missile, {55% chance it hits a decoy|p} instead',
    desc: 'Each time an enemy SAM fires at one of your missiles, there is a 55% chance it hits a decoy instead. The SAM still has to reload and your missile flies on.',
    words: ['sam_breaker'], answers: ['sam_covered', 'shot_my_missiles'] },
  { id: 'hypersonic_missiles', name: 'Hypersonic Missiles', tags: ['nuke', 'aggro'], ai: { nukes: 1, antiSam: 2 }, tier: 3,
    short: 'Your missiles fly {2x faster|g}; a SAM that stops one {reloads 3x slower|p}',
    desc: 'Your missiles fly twice as fast, and a SAM that does shoot one down needs three times as long to reload.',
    words: ['sam_breaker'], answers: ['sam_clump', 'shot_my_missiles', 'sam_covered'] },
  { id: 'sead_doctrine', name: 'SEAD Doctrine', tags: ['air', 'aggro'], ai: { airships: 1, antiSam: 3 }, tier: 2,
    short: "Airship drops {destroy enemy SAMs|p} within 15 tiles; bombers sent at SAMs {can't be shot down|g}",
    desc: "Troops dropped by your Airships destroy every enemy SAM Launcher within 15 tiles of where they land, and Bomber Strikes aimed at a SAM can't be shot down.",
    words: ['sam_breaker', 'airship_threat'], answers: ['sam_clump', 'sam_covered', 'shot_my_missiles', 'downed_my_airships'] },
  // ---- answer to airships, for mech nations ----
  { id: 'airborne_mechs', name: 'Airborne Mechs', tags: ['mech', 'air'], ai: { mechs: 1, antiAir: 3 }, tier: 3,
    short: 'Mechs move {2x faster|g} over land and water and {shoot down Airships|p}, but deal {80% less damage|r}',
    desc: 'Your Mechs move twice as fast over land and water and shoot down enemy Airships in range - but their shells deal 80% less damage to everything else.',
    words: ['anti_air', 'amphibious'], answers: ['airship_threat', 'airport', 'overseas', 'downed_my_airships'] },
  { id: 'nuclear_deterrence', name: 'Nuclear Deterrence', tags: ['nuke', 'defense'], ai: {}, tier: 2,
    short: 'If you are nuked, an atom bomb {fires back automatically|p}',
    desc: 'If someone nukes you while you have a ready Missile Silo and enough gold, an atom bomb automatically fires back at their nearest silo (or a city).',
    words: ['deterrent', 'nuclear'], answers: ['nuclear', 'nuke_armed', 'cheap_nukes', 'nuked_me'] },
];
const BY_ID = Object.fromEntries(RESEARCH.map((r) => [r.id, r]));

const has = (p, id) => !!(p && p.researches && p.researches.has(id));

// ---- multipliers used across the sim ----
const effects = {
  buildDiscount: (p) => (has(p, 'mass_production') ? 0.85 : 1),
  goldMultiplier: (p, attacking) => {
    let m = 1;
    if (has(p, 'war_economy') && attacking) m *= 1.3;
    if (has(p, 'industrial_mobilization')) m *= 1.25;
    if (has(p, 'military_district')) m *= 0.7;
    return m;
  },
  maxTroopsMultiplier: (p) => (has(p, 'industrial_mobilization') ? 0.9 : 1),
  cityTroopBonus: (p) => (has(p, 'military_district') ? 375000 : 250000),
  troopGrowthMultiplier: (p, connectedFactories) => (has(p, 'military_rail') && connectedFactories >= 2 ? 1.2 : 1),
  attackSpeedMultiplier: (p) => (has(p, 'strategic_logistics') ? 1.25 : 1),
  attackerLossMultiplier: (p, vsPlayer) => (vsPlayer && has(p, 'close_air_support') ? 0.75 : 1),
  boatCapacity: (p) => (has(p, 'amphibious_warfare') ? 1.5 : 1),
  boatSpeed: (p) => (has(p, 'amphibious_warfare') ? 1.5 : 1) * (has(p, 'strategic_logistics') ? 1.5 : 1),
  boatMax: (p) => (has(p, 'amphibious_warfare') ? 5 : 3),
  landingBonus: (p) => (has(p, 'dday') ? 1.15 : 1),
  tradeGoldMultiplier: (p) => (has(p, 'naval_base') ? 1.25 : 1),
  trainGoldMultiplier: (p) => (has(p, 'military_rail') ? 2 : 1),
  trainRateMultiplier: (p) => (has(p, 'military_industrial') ? 2 : 1),
  warshipCap: (p) => 3 + (has(p, 'naval_base') ? 2 : 0),
  warshipRepairMultiplier: (p) => (has(p, 'naval_base') ? 5 : 1),
  atomCost: (p) => (has(p, 'tactical_nukes') ? 500000 : 1000000),
  atomMagnitude: (p) => (has(p, 'tactical_nukes') ? { inner: 8, outer: 16 } : { inner: 12, outer: 30 }),
  siloCooldownMultiplier: (p) => (has(p, 'tactical_nukes') ? 0.5 : 1),
  samRangeBonus: (p) => (has(p, 'fighter_networks') ? 30 : 0),
  wallDamageMultiplier: (p) => (has(p, 'hardened_infra') ? 0.5 : 1),
  // Fraction of a warship's health a defense post shell takes off. Deliberately tiny: posts drive ships
  // off over time instead of deleting them. Coastal Defense Network is what makes them actually dangerous.
  // One doctrine may raise ONE building type's ceiling from 3 to 4, and that last level is a big jump.
  // ---- air power ----
  airshipCapBonus: (p) => (has(p, 'airbase_network') ? 1 : 0),
  airshipCostMultiplier: (p) => (has(p, 'airbase_network') ? 0.7 : 1),
  airshipCapacityMultiplier: (p) => (has(p, 'strategic_airlift') ? 2 : 1),
  airshipSpeedMultiplier: (p) => (has(p, 'strategic_airlift') ? 1.5 : 1),
  airshipRangeBonus: (p) => (has(p, 'strategic_airlift') ? 120 : 0),
  airdropBonus: (p) => (has(p, 'airborne_doctrine') ? 1.35 : 1),
  samNearAirport: (p) => has(p, 'airbase_network'),
  interceptsAirships: (p) => has(p, 'interceptor_screen'),
  interceptorRangeBonus: (p) => (has(p, 'fighter_networks') ? 40 : 0),
  interceptorChanceMultiplier: (p) => (has(p, 'fighter_networks') ? 1.4 : 1),
  maxLevelBonus: (p, type) => ((type === 'city' && has(p, 'megacity')) || (type === 'factory' && has(p, 'heavy_industry')) ? 1 : 0),
  artilleryRangeBonus: (p) => (has(p, 'field_engineering') ? 15 : 0),
  artilleryReloadMultiplier: (p) => (has(p, 'field_engineering') ? 0.7 : 1),
  artilleryDamageMultiplier: (p) => (has(p, 'field_engineering') ? 1.5 : 1),
  defensePostShipDamagePct: (p) => (has(p, 'coastal_defense') ? 0.015 : 0.0025),
  defensePostShipRange: (p) => (has(p, 'coastal_defense') ? 150 : 75),
  defensePostShellRate: (p) => (has(p, 'coastal_defense') ? 25 : 40),   // ticks between shells
  // mechs
  mechHpMultiplier: (p) => (has(p, 'heavy_mech') ? 2.5 : 1),
  mechSpeedMultiplier: (p) => (has(p, 'heavy_mech') ? 0.6 : 1) * (has(p, 'airborne_mechs') ? 2 : 1),
  mechRangeBonus: (p) => (has(p, 'longrange_mech') ? 10 : 0),
  mechDamageMultiplier: (p) => (has(p, 'mech_weapons') ? 1.6 : 1) * (has(p, 'airborne_mechs') ? 0.2 : 1),
  mechCooldownMultiplier: (p) => (has(p, 'rapidfire_mech') ? 0.6 : 1),
  mechStompBonus: (p) => (has(p, 'assault_mech') ? 2 : 0),
  mechBreachMultiplier: (p) => (has(p, 'assault_mech') ? 3 : 1),
  mechCostMultiplier: (p) => (has(p, 'mech_production') ? 0.6 : 1) * (has(p, 'military_industrial') ? 0.75 : 1),
  mechCap: (p) => 3 + (has(p, 'mech_production') ? 1 : 0),
  mechAmphibious: (p) => has(p, 'amphibious_mech'),               // the naval-combat doctrine
  mechCrossesWater: (p) => has(p, 'amphibious_mech') || has(p, 'airborne_mechs'),
  mechAntiAir: (p) => has(p, 'airborne_mechs'),
  // ---- SAM counters ----
  clusterMunitions: (p) => has(p, 'cluster_munitions'),
  decoyChance: (p) => (has(p, 'decoy_warheads') ? 0.55 : 0),
  missileSpeedMultiplier: (p) => (has(p, 'hypersonic_missiles') ? 2 : 1),
  samReloadPenalty: (p) => (has(p, 'hypersonic_missiles') ? 3 : 1),
  sead: (p) => has(p, 'sead_doctrine'),
};

module.exports = { RESEARCH, RESEARCH_BY_ID: BY_ID, has, effects };
