'use strict';
// Research doctrines. Every entry is fully wired into the simulation (see the `effects` comments and the
// helpers below, which the other systems query). `ai` hints tell the nation AI how to change behaviour.

const RESEARCH = [
  // ---- economy / logistics ----
  { id: 'war_economy', name: 'War Economy', tags: ['econ', 'aggro'], ai: { aggression: 1.4 }, tier: 2,
    short: '{+30% gold|g} while attacking a nation',
    desc: '+30% gold income while you are attacking an enemy nation. (Your nation fights harder when it fights more.)' },
  { id: 'mass_production', name: 'Mass Production', tags: ['econ', 'build'], ai: { build: 1.3 }, tier: 2,
    short: '{-15% cost|g} on every building and wall',
    desc: 'All buildings and walls cost 15% less gold.' },
  { id: 'industrial_mobilization', name: 'Industrial Mobilization', tags: ['econ'], ai: { build: 1.2 }, tier: 2,
    short: '{+25% gold|g}, but {-10% max troops|r}',
    desc: 'Cities are retooled for war: +25% gold income, but your max troops are 10% lower.' },
  { id: 'military_rail', name: 'Military Rail', tags: ['econ', 'defense'], ai: { factories: 2 }, tier: 2,
    short: '{+20% troop growth|g} with 2+ linked factories; trains pay {2x gold|g}',
    desc: 'Rail moves armies: +20% troop growth while you own 2+ factories connected by rail. Trains also carry 2x gold.' },
  { id: 'strategic_logistics', name: 'Strategic Logistics', tags: ['aggro'], ai: { aggression: 1.2 }, tier: 2,
    short: 'Attacks advance {25% faster|g}; boats sail {50% faster|g}',
    desc: 'Your attacks advance 25% faster and boats are 50% faster.' },
  { id: 'military_industrial', name: 'Military Industrial Complex', tags: ['mech', 'econ'], ai: { factories: 2, mechs: 1 }, tier: 3,
    short: 'Factories run trains {2x as often|g}; Mechs {-25% cost|g}',
    desc: 'Factories spawn trains twice as often and Mechs cost 25% less.' },
  // ---- defense ----
  { id: 'defensive_position', name: 'Defensive Position', tags: ['defense'], ai: { posts: 2 }, tier: 1,
    short: 'Defense Posts hit attackers with {15% of your troops|g}; garrison them for more',
    desc: 'Defense Posts fire on nearby attackers with 15% of your troops as firepower. Click a post to garrison 10% of your troops into it for more.' },
  { id: 'coastal_defense', name: 'Coastal Defense Network', tags: ['defense', 'navy'], ai: { posts: 1.5 }, tier: 2,
    short: 'Posts shell {every ship|p} at {2x range|g} for {1.5% of a warship|p}; landings near them lose {30% troops|p}',
    desc: 'Defense Posts become coastal batteries: they shell every enemy ship (not just warships) at double range and a faster rate, each shell taking 1.5% of a warship, and boats landing near them lose 30% of their troops.' },
  { id: 'hardened_infra', name: 'Hardened Infrastructure', tags: ['defense'], ai: {}, tier: 2,
    short: 'Buildings outside a blast core {survive nukes|g}; walls take {half damage|g}',
    desc: 'Structures outside a nuke\'s core survive the blast, and walls take half damage from everything.' },
  { id: 'military_district', name: 'Military Districts', tags: ['defense', 'aggro'], ai: { aggression: 1.15 }, tier: 1,
    short: 'Cities give {+375K max troops|g} (was 250K), but {-30% gold|r}',
    desc: 'Cities give +375K max troops instead of +250K, but your gold income is 30% lower.' },
  { id: 'fighter_networks', name: 'Fighter Networks', tags: ['air', 'defense'], ai: {}, tier: 1,
    short: 'Enemy bombers over you {~60% shot down|p}; your SAMs {+30 range|g}',
    desc: 'Enemy bombers over your territory are shot down 60% of the time, and your SAMs get +30 range.' },
  // ---- mech doctrines ----
  { id: 'heavy_mech', name: 'Heavy Mech Doctrine', tags: ['mech', 'defense'], ai: { mechs: 1 }, tier: 2,
    short: 'Mechs {2.5x HP|g}, but {-40% speed|r}',
    desc: 'Your Mechs have 2.5x HP but move 40% slower.' },
  { id: 'assault_mech', name: 'Assault Mech Doctrine', tags: ['mech', 'aggro'], ai: { mechs: 1, aggression: 1.2 }, tier: 2,
    short: 'Mech stomps {+2 radius|g}; break walls and posts {3x faster|p}',
    desc: 'Mech stomps clear a wider area (radius +2) and break walls and defense posts 3x faster.' },
  { id: 'mech_production', name: 'Mech Production', tags: ['mech', 'econ'], ai: { mechs: 2 }, tier: 3,
    short: 'Mechs {-40% cost|g}; {+1 Mech|g} allowed',
    desc: 'Mechs cost 40% less and you may field one extra.' },
  { id: 'mech_weapons', name: 'Mech Weapons Systems', tags: ['mech', 'aggro'], ai: { mechs: 1 }, tier: 2,
    short: 'Mech shells {+60% damage|g} and {one-shot buildings|p}',
    desc: 'Mech cannon shells deal 60% more damage and can one-shot structures.' },
  { id: 'longrange_mech', name: 'Long-Range Mech Systems', tags: ['mech'], ai: { mechs: 1 }, tier: 2,
    short: 'Mech range {+10 tiles|g}',
    desc: 'Mech cannon range +10 tiles.' },
  { id: 'rapidfire_mech', name: 'Rapid-Fire Mech Systems', tags: ['mech', 'aggro'], ai: { mechs: 1 }, tier: 3,
    short: 'Mech cannon and stomp {reload 40% faster|g}',
    desc: 'Mech cannon and stomp cooldowns are 40% shorter.' },
  { id: 'amphibious_mech', name: 'Amphibious Mechs', tags: ['mech', 'navy'], ai: { mechs: 1 }, tier: 2,
    short: 'Mechs {cross water|g}, hit warships for {95% of their health|p}, spot subs within {30 tiles|p}',
    desc: 'Your Mechs can wade across water and are built to kill navies: each shell takes 95% of a warship\u2019s health, they reach 50% further at sea, and they spot submarines within 30 tiles.' },
  // ---- navy ----
  { id: 'coastal_bombardment', name: 'Coastal Bombardment', tags: ['navy', 'aggro'], ai: { warships: 2, aggression: 1.1 }, tier: 2,
    short: 'Warships shell coastal land within {40 tiles|p}; warships {+300K cost per 10 owned|r}',
    desc: 'Warships shell enemy coastal land within 40 tiles, turning it neutral and killing troops. Warships cost +300K per 10 owned.' },
  { id: 'submarine_warfare', name: 'Submarine Warfare', tags: ['navy'], ai: { subs: 1 }, tier: 3,
    short: 'Unlocks {Submarines|g}: invisible, fire {3 missiles|p} every 90s that ignore SAMs',
    desc: 'Unlock Submarines (2.5x a warship): invisible unless within 10 tiles of an enemy warship, they fire volleys of 3 missiles every 90s that each wreck one structure and slip past SAMs.' },
  { id: 'nuclear_subs', name: 'Nuclear Submarines', tags: ['navy', 'nuke'], ai: { subs: 1, nukes: 1 }, tier: 3,
    short: 'Submarines {launch atom bombs|g} from anywhere at sea',
    desc: 'Your Submarines also carry atom bombs (normal cost) launched from anywhere at sea.' },
  { id: 'amphibious_warfare', name: 'Amphibious Warfare', tags: ['navy', 'aggro'], ai: { boats: 2 }, tier: 2,
    short: 'Boats carry {+50% troops|g}, sail {50% faster|g}; {5 boats|g} at once',
    desc: 'Transports carry 50% more troops, sail 50% faster, and you may have 5 boats at once.' },
  { id: 'naval_mines', name: 'Naval Mines', tags: ['navy', 'defense'], ai: { mines: 1 }, tier: 1,
    short: 'Unlocks {Naval Mines|g} (50K): {sink any enemy ship|p} within 2 tiles',
    desc: 'Lay Mines (50K) on the sea. Any enemy ship or boat passing within 2 tiles is destroyed.' },
  { id: 'naval_base', name: 'Naval Bases', tags: ['navy', 'econ'], ai: { warships: 1 }, tier: 2,
    short: '{+25% trade gold|g}, warships repair {5x faster|g}, {+2 warships|g}',
    desc: 'Ports become Naval Bases: +25% trade-ship gold, warships repair 5x faster near them, +2 warship cap.' },
  { id: 'dday', name: 'D-Day', tags: ['navy', 'aggro'], ai: { boats: 1.5 }, tier: 1,
    short: 'Landings hit with {+15% troops|g} and take the beach {with no losses|g}',
    desc: 'Boat invasions hit the beach with +15% troops and take the landing tile instantly with no losses.' },
  // ---- air ----
  { id: 'strategic_bombers', name: 'Strategic Bombers', tags: ['air', 'aggro'], ai: { bombers: 1 }, tier: 2,
    short: "Unlocks {Bomber Strikes|g} (300K): {destroy one enemy building|p}; SAMs can't stop them",
    desc: 'Order Bomber strikes (300K) from any Missile Silo: a bomber flies up to 250 tiles and destroys one enemy structure. SAMs can\'t touch it; Fighter Networks can.' },
  { id: 'close_air_support', name: 'Close Air Support', tags: ['air', 'aggro'], ai: { aggression: 1.25 }, tier: 2,
    short: 'Your attacks on nations lose {25% fewer troops|g}',
    desc: 'Your ground attacks on players lose 25% fewer troops.' },
  // ---- strategic weapons ----
  { id: 'tactical_nukes', name: 'Tactical Nuclear Weapons', tags: ['nuke', 'aggro'], ai: { nukes: 2 }, tier: 2,
    short: 'Atom bombs {400K|g} (was 750K), silos {reload 2x faster|g}, blasts {smaller|r}',
    desc: 'Atom bombs cost 400K instead of 750K, silos reload twice as fast, but atom blasts are smaller (8/16).' },
  { id: 'mirv', name: 'MIRV Engineering', tags: ['nuke'], ai: { nukes: 1 }, tier: 3,
    short: 'Hydrogen bombs split into {5 warheads|p} across 45 tiles',
    desc: 'Hydrogen bombs split into 5 atom-sized warheads scattered up to 45 tiles around the target.' },
  { id: 'field_engineering', name: 'Field Engineering', tags: ['defense', 'mech'], ai: { defensive: 1, mechs: 1 }, tier: 2,
    short: 'Unlocks {Repair Yard|g}; Artillery {+15 range|g}, {30% faster reload|g}, {+50% damage|g}',
    desc: 'Unlocks the Repair Yard: it heals your Mechs and rebuilds damaged walls in range. Artillery Batteries also get +15 range, reload 30% faster and hit 50% harder.' },
  { id: 'megacity', name: 'Megacity Planning', tags: ['econ'], ai: { build: 1.1 }, tier: 3,
    short: 'Cities reach {level 4|g}, the biggest gold jump there is',
    desc: 'Cities can reach level 4 instead of 3, and a level-4 City is worth far more than the step before it.' },
  { id: 'heavy_industry', name: 'Heavy Industry', tags: ['econ'], ai: { factories: 3 }, tier: 3,
    short: 'Factories reach {level 4|g}; trains pay {+35% per level|g} above 2',
    desc: 'Factories can reach level 4. Every level above 2 also makes that factory\u2019s trains pay 35% more.' },
  { id: 'strategic_airlift', name: 'Strategic Airlift', tags: ['air'], ai: { airships: 2 }, tier: 3,
    short: 'Airships carry {10% of troops|g} (was 5%), {+50% speed|g}, {+120 range|g}',
    desc: 'Airships carry 10% of your troops instead of 5%, fly 50% faster and reach 120 tiles further.' },
  { id: 'airbase_network', name: 'Airbase Network', tags: ['air'], ai: { airships: 1 }, tier: 2,
    short: '{+1 airship|g}, airships {-30% cost|g}, SAMs {allowed near your Airport|g}',
    desc: 'A fourth airship, 30% cheaper airships, and SAM Launchers may finally sit next to your Airport.' },
  { id: 'airborne_doctrine', name: 'Airborne Doctrine', tags: ['air', 'aggro'], ai: { airships: 1, aggression: 1.1 }, tier: 2,
    short: 'Airdropped troops land {35% stronger|g}',
    desc: 'Troops dropped by airship land 35% stronger.' },
  { id: 'interceptor_screen', name: 'Interceptor Screen', tags: ['defense', 'air'], ai: { defensive: 1 }, tier: 2,
    short: 'Enemy airships near your cities are {45% shot down|p}',
    desc: 'Fighters scramble from your Cities, SAMs and Airport: enemy airships passing within 60 tiles have a 45% chance of being shot down. The only answer to an airlift.' },
  // ---- answers to SAM umbrellas ----
  { id: 'cluster_munitions', name: 'Cluster Munitions', tags: ['nuke', 'aggro'], ai: { nukes: 1, antiSam: 3 }, tier: 2,
    short: 'Unlocks {Cluster Strike|g}: {8 small missiles|p} at once, and each SAM can only stop one',
    desc: 'Unlocks the Cluster Strike (1.5M) from any Missile Silo: eight small missiles fly at once and scatter over the target. A SAM stops one missile per reload, so a volley saturates an air defence network that would swallow a single bomb.' },
  { id: 'decoy_warheads', name: 'Decoy Warheads', tags: ['nuke'], ai: { nukes: 1, antiSam: 2 }, tier: 2,
    short: 'Enemy SAMs have a {55% chance|p} to waste their shot on a decoy',
    desc: 'Every missile you fire is escorted by decoys. When an enemy SAM engages one, there is a 55% chance it hits a decoy: the SAM still spends its reload and your missile flies on.' },
  { id: 'hypersonic_missiles', name: 'Hypersonic Missiles', tags: ['nuke', 'aggro'], ai: { nukes: 1, antiSam: 2 }, tier: 3,
    short: 'Your missiles fly {2x faster|g}; a SAM that stops one {reloads 3x slower|p}',
    desc: 'Your missiles fly twice as fast, and a SAM that does manage to intercept one needs three times as long to reload - leaving the sky open for whatever you fire next.' },
  { id: 'sead_doctrine', name: 'SEAD Doctrine', tags: ['air', 'aggro'], ai: { airships: 1, antiSam: 3 }, tier: 2,
    short: 'Airship landings {destroy enemy SAMs|p} within 15 tiles; bombers sent at SAMs {can\'t be shot down|g}',
    desc: 'Suppression of Enemy Air Defences. Troops dropped by airship wreck every enemy SAM Launcher within 15 tiles of where they land, and a Bomber Strike aimed at a SAM ignores Fighter Networks.' },
  // ---- answer to airships, for mech nations ----
  { id: 'airborne_mechs', name: 'Airborne Mechs', tags: ['mech', 'air'], ai: { mechs: 1, antiAir: 3 }, tier: 3,
    short: 'Mechs {+100% speed|g}, {cross water|g}, {shoot down airships|p}, but deal {-80% damage|r}',
    desc: 'Your Mechs are refitted as jump-jet gunships: twice the speed, they cross water and land alike, and their cannon tracks and destroys enemy airships in range. The trade: their shells deal 80% less damage to everything else.' },
  { id: 'nuclear_deterrence', name: 'Nuclear Deterrence', tags: ['nuke', 'defense'], ai: {}, tier: 2,
    short: 'If nuked, an atom bomb {fires back automatically|p} (needs a ready silo + 750K)',
    desc: 'If someone nukes you while you have a ready silo and 750K gold, an atom bomb automatically answers at their nearest silo (or city).' },
];
const BY_ID = Object.fromEntries(RESEARCH.map((r) => [r.id, r]));

const has = (p, id) => !!(p && p.researches && p.researches.has(id));

// ---- multipliers used across the sim ----
const effects = {
  buildDiscount: (p) => (has(p, 'mass_production') ? 0.85 : 1),
  goldMultiplier: (p, attacking) => {
    let m = 1;
    if (has(p, 'war_economy') && attacking) m *= 1.3;
    if (has(p, 'industrial_mobilization')) m *= 1.25;
    if (has(p, 'military_district')) m *= 0.7;
    return m;
  },
  maxTroopsMultiplier: (p) => (has(p, 'industrial_mobilization') ? 0.9 : 1),
  cityTroopBonus: (p) => (has(p, 'military_district') ? 375000 : 250000),
  troopGrowthMultiplier: (p, connectedFactories) => (has(p, 'military_rail') && connectedFactories >= 2 ? 1.2 : 1),
  attackSpeedMultiplier: (p) => (has(p, 'strategic_logistics') ? 1.25 : 1),
  attackerLossMultiplier: (p, vsPlayer) => (vsPlayer && has(p, 'close_air_support') ? 0.75 : 1),
  boatCapacity: (p) => (has(p, 'amphibious_warfare') ? 1.5 : 1),
  boatSpeed: (p) => (has(p, 'amphibious_warfare') ? 1.5 : 1) * (has(p, 'strategic_logistics') ? 1.5 : 1),
  boatMax: (p) => (has(p, 'amphibious_warfare') ? 5 : 3),
  landingBonus: (p) => (has(p, 'dday') ? 1.15 : 1),
  tradeGoldMultiplier: (p) => (has(p, 'naval_base') ? 1.25 : 1),
  trainGoldMultiplier: (p) => (has(p, 'military_rail') ? 2 : 1),
  trainRateMultiplier: (p) => (has(p, 'military_industrial') ? 2 : 1),
  warshipCap: (p) => 3 + (has(p, 'naval_base') ? 2 : 0),
  warshipRepairMultiplier: (p) => (has(p, 'naval_base') ? 5 : 1),
  atomCost: (p) => (has(p, 'tactical_nukes') ? 400000 : 750000),
  atomMagnitude: (p) => (has(p, 'tactical_nukes') ? { inner: 8, outer: 16 } : { inner: 12, outer: 30 }),
  siloCooldownMultiplier: (p) => (has(p, 'tactical_nukes') ? 0.5 : 1),
  samRangeBonus: (p) => (has(p, 'fighter_networks') ? 30 : 0),
  wallDamageMultiplier: (p) => (has(p, 'hardened_infra') ? 0.5 : 1),
  // Fraction of a warship's health a defense post shell takes off. Deliberately tiny: posts drive ships
  // off over time instead of deleting them. Coastal Defense Network is what makes them actually dangerous.
  // One doctrine may raise ONE building type's ceiling from 3 to 4, and that last level is a big jump.
  // ---- air power ----
  airshipCapBonus: (p) => (has(p, 'airbase_network') ? 1 : 0),
  airshipCostMultiplier: (p) => (has(p, 'airbase_network') ? 0.7 : 1),
  airshipCapacityMultiplier: (p) => (has(p, 'strategic_airlift') ? 2 : 1),
  airshipSpeedMultiplier: (p) => (has(p, 'strategic_airlift') ? 1.5 : 1),
  airshipRangeBonus: (p) => (has(p, 'strategic_airlift') ? 120 : 0),
  airdropBonus: (p) => (has(p, 'airborne_doctrine') ? 1.35 : 1),
  samNearAirport: (p) => has(p, 'airbase_network'),
  interceptsAirships: (p) => has(p, 'interceptor_screen'),
  interceptorRangeBonus: (p) => (has(p, 'fighter_networks') ? 40 : 0),
  interceptorChanceMultiplier: (p) => (has(p, 'fighter_networks') ? 1.4 : 1),
  maxLevelBonus: (p, type) => ((type === 'city' && has(p, 'megacity')) || (type === 'factory' && has(p, 'heavy_industry')) ? 1 : 0),
  artilleryRangeBonus: (p) => (has(p, 'field_engineering') ? 15 : 0),
  artilleryReloadMultiplier: (p) => (has(p, 'field_engineering') ? 0.7 : 1),
  artilleryDamageMultiplier: (p) => (has(p, 'field_engineering') ? 1.5 : 1),
  defensePostShipDamagePct: (p) => (has(p, 'coastal_defense') ? 0.015 : 0.0025),
  defensePostShipRange: (p) => (has(p, 'coastal_defense') ? 150 : 75),
  defensePostShellRate: (p) => (has(p, 'coastal_defense') ? 25 : 40),   // ticks between shells
  // mechs
  mechHpMultiplier: (p) => (has(p, 'heavy_mech') ? 2.5 : 1),
  mechSpeedMultiplier: (p) => (has(p, 'heavy_mech') ? 0.6 : 1) * (has(p, 'airborne_mechs') ? 2 : 1),
  mechRangeBonus: (p) => (has(p, 'longrange_mech') ? 10 : 0),
  mechDamageMultiplier: (p) => (has(p, 'mech_weapons') ? 1.6 : 1) * (has(p, 'airborne_mechs') ? 0.2 : 1),
  mechCooldownMultiplier: (p) => (has(p, 'rapidfire_mech') ? 0.6 : 1),
  mechStompBonus: (p) => (has(p, 'assault_mech') ? 2 : 0),
  mechBreachMultiplier: (p) => (has(p, 'assault_mech') ? 3 : 1),
  mechCostMultiplier: (p) => (has(p, 'mech_production') ? 0.6 : 1) * (has(p, 'military_industrial') ? 0.75 : 1),
  mechCap: (p) => 3 + (has(p, 'mech_production') ? 1 : 0),
  mechAmphibious: (p) => has(p, 'amphibious_mech'),               // the naval-combat doctrine
  mechCrossesWater: (p) => has(p, 'amphibious_mech') || has(p, 'airborne_mechs'),
  mechAntiAir: (p) => has(p, 'airborne_mechs'),
  // ---- SAM counters ----
  clusterMunitions: (p) => has(p, 'cluster_munitions'),
  decoyChance: (p) => (has(p, 'decoy_warheads') ? 0.55 : 0),
  missileSpeedMultiplier: (p) => (has(p, 'hypersonic_missiles') ? 2 : 1),
  samReloadPenalty: (p) => (has(p, 'hypersonic_missiles') ? 3 : 1),
  sead: (p) => has(p, 'sead_doctrine'),
};

module.exports = { RESEARCH, RESEARCH_BY_ID: BY_ID, has, effects };
